apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ include "straiker-inference.namespace" . }}
  labels:
    {{- include "straiker-inference.labels" . | nindent 4 }}
