apiVersion: v1
kind: Service
metadata:
  name: straiker-frontend-service
  namespace: {{ include "frontend.namespace" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: straiker-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
