apiVersion: v1
kind: Service
metadata:
  name: straiker-defend
  namespace: {{ include "defend.namespace" . }}
  labels:
    {{- include "defend.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: straiker-defend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
